clear; close all; clf;
%% Run all plot scripts
tic
plot_fig2_adjMat
plot_fig3_MimoDecomposed
plot_fig4_interChannelMaxCorrelationMatrix
plot_fig5_histogramsFbMatrix
plot_fig6_corrOctaveBand
plot_fig7_histogramsMixingConfigs
plot_fig8_MimoVsSimoVelvet
toc
